"""auth added

Revision ID: 005
Revises: 004
Create Date: 2023-12-23 21:09:10.345284

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import path_to_custom_types_py_file


# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
    )
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "user", sa.Column("is_superuser", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "user", sa.Column("is_verified", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "user", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "name")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "is_active")
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
